# NCI QCIF workshop with PBS
snippets: "/snippets_library/NCI_pbs"

local:
  prompt: "[user@laptop ~]$"

remote:
  name: "Gadi"
  login: "gadi.nci.org.au"
  host: "gadi.nci.org.au"
  node: gadi-login-04
  location: "Gadi"
  homedir: "/home/123/yourUsername"
  user: "yourUsername"
  prompt: "[yourUsername@gadi-login-04 ~ ~]$ "
  bash_shebang: "#!/bin/bash -l"

sched:
  name: "PBS"
  submit:
    name: "qsub"
    options: ""
    iopt: ""
  status: "qstat"
  flag:
    user: "-u yourUsername"
    interactive: "-l mem=512M,h_rt=2:00:00"
    name: "-N"
    histdetail: "-j"
    time: "-l h_rt="
    queue: "-q"
  del: "qdel"
  interactive: "qrsh"
  info: "qhost"
  comment: "#$ "
  hist: "jobhist"
  hist_filter: ""
  bash_shebang: "#!/bin/bash -l"

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 15-modules
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility
